### ISSUE TITLE
Show uploaded Pictures/Images on comments/threads

### ISSUE THREAD

**Issue by linuxissuper** [harrisoncramer/gitlab.nvim#118]
## Feature Description
We work a lot with screenshots and upload them as a comment to gitlab  
so it would be very nice to see the picture in neovim   
  
with this plugin (https://github.com/3rd/image.nvim) it is possible to view images in markdown files  
and since gitlab comments are also markdown it should also work? (just thinking loud 😅)  
  
for example when editing the comment, the picture should be shown  
![image](https://github.com/harrisoncramer/gitlab.nvim/assets/74221543/b587f919-4824-4c6f-92b2-b3c7c645f5b4)
  
markdown file with the same screenshot (and using image.nvim)   
![image](https://github.com/harrisoncramer/gitlab.nvim/assets/74221543/12d2e240-dcfc-4434-b437-035f7f8222c6)

**Comment by harrisoncramer** [comment]
Hello, thanks for the feature request!

Image support would be very cool, but is out of scope for this plugin, until/unless image rendering is part of Neovim core. 

The plugin you reference has several third-party dependencies, and additionally only works with a particular terminal setup. However, since the comments are just markdown views, nothing is stopping you or anyone else from installing that plugin and using it alongide this plugin. But it's not (yet) something that I plan to integrate into `gitlab.nvim` directly.
