### ISSUE TITLE
Ability to list issue relate to a repo and comment

### ISSUE THREAD

**Issue by nguyenanhhao221** [harrisoncramer/gitlab.nvim#143]
Thank you for the amazing plugin, It help my work flow a lot.
However  I notice that it lack the ability to view the "Issues" list in the current repo. 

I think it would help a lot.

## Feature Description

- Able to view issue with something like 
```lua
require("gitlab").issues()
```

**Comment by harrisoncramer** [comment]
Hey, thank you for filing this feature request and for the kind words! 

I'm not super familiar with issues as it's not a Gitlab feature that I've used. Could you please describe the essential features that you'd like to have implemented?

Based on my understanding, looking at Gitlab, it doesn't seem that Issues are tied to a particular MR. The primary purpose of this plugin (for now) is achieving efficient MR review flows in Neovim. Not that we couldn't add this, but there are other MR workflow features (such as creating an MR, merging an MR, etc) that should probably take priority over this.

**Comment by nguyenanhhao221** [comment]
Thank you for your clarification, I would say that this feature is quite low prio if the main focus is in improving the MR workflow. 

For my use case usually my company also need to discuss , comment of a issue ticket that was assign to an individual before begin to move on to open an MR. And I would love to be able to do this without leaving Neovim. 

However I hope you can still leave this open as I am also trying to learn to build Neovim plugin and I would love to be able to implement this myself.

**Comment by harrisoncramer** [comment]
I'm going to close this out because it's not something that's on the immediate horizon for this plugin. 

Building out a UI for issues is a substantial lift that's not necessarily tied to merge requests. 

If someone is interested in taking that on please make sure to put up a proof of concept so that we can discuss the implementation before you spend too much time on it, and drop a comment here and I'll reopen this issue.
