### ISSUE TITLE
Document available commands from `gitlab` and `gitlab.server`

### ISSUE THREAD

**Issue by bmendric** [harrisoncramer/gitlab.nvim#153]
## Feature Description
While reading through the docs here I found myself going through code and @harrisoncramer 's nvim config to try and understand what commands are available from `require("gitlab").XXX`. Would be great to have a list documented somewhere, preferably in vimdocs

**Comment by harrisoncramer** [comment]
Hey @bmendric thank you for filing this issue. All of the commands meant to be used by users are under the keybindings section in the Readme.

https://github.com/harrisoncramer/gitlab.nvim#keybindings

However, it probably makes sense to move most of the readme to a `doc` folder and add tags, so that you can run `:help` commands in Neovim. Is that what you had in mind?

**Comment by bmendric** [comment]
@harrisoncramer yea, I think making the docs searchable via `:help` with tags would be a significant benefit.

**Comment by harrisoncramer** [comment]
I've added help documentation at `/doc` and which can be accessed via `:help gitlab.nvim` so I'm closing this now. I've moved the more technical part of the Readme into this file as well. Thank you for the suggestion.
