### ISSUE TITLE
Save contents of popup to backup register when quitting

### ISSUE THREAD

**Issue by jakubbortlik** [harrisoncramer/gitlab.nvim#177]
## Feature Description
I'd like to have the contents of a comment popup saved to a backup register when hitting `q` to quit, similar to saving to `backup_register` when `perform_action` is triggered. The purpose would be to temporarily interrupt editing a comment, do some work, and then open the comment again and paste the previously typed contents back in - I'd like to use the unnamed register (`:h quotequote`) so that I could simply paste with `p` without referencing the register. That's why this should be a separate register, other than the current `backup_register` whose purpose it is (in my workflow) to be able to use the finished comment outside of `neovim`, so that the `+` register is more suitable for it.

This would be a kind of primitive "cache" alternative to what is possible in Gitlab online. I'll be glad to open a PR on this. Within the PR, I'd like to make some more improvements:
1. Allow a list of registers to be used (e.g., `backup_register = { "+", "b" }`). This would make the method a little more robust, in case the `+` register got overwritten by some other copy action in/outside of `neovim`. This should not be a breaking change and a string should still be accepted, I guess.
2. If no backup register is defined, save to a global variable instead (something like `vim.g.gitlab_note_backup`), and show information about this to the user, something like "Buffer contents saved to g:gitlab_note_backup. Use :let @+=g:gitlab_note_backup to save to system clipboard. See :h gitlab.nvim.backup-register for how to get rid of this message.") This message could be suppressed in the settings even if not using any backup register. This would address the [issue](https://github.com/harrisoncramer/gitlab.nvim/pull/163#issuecomment-1905739639) raised by @briandipalma that a backup register should be used by default in order to prevent data loss.

**Comment by harrisoncramer** [comment]
I like this idea, but would refine it slightly: Quitting any editable popup buffer before performing an action should save the buffer contents to a predefined register. Couple of things though:

1. I do not think we should introduce a breaking change in the old settings, since it's a completely different feature from the old "backup register" concept. That is a temporary hotfix that I intend to remove completely once we've sorted out the bugs with adding single-line discussions (done) and multi-line discussions (in-progress). It's not permanent.
2. You could call this new setting "temp_register" and make it a list, like you describe.
3. I would introduce a hook into the popup abstraction that does this automatically rather than creating a new "q" keybinding. See the documentation here: https://github.com/MunifTanjim/nui.nvim/tree/main/lua/nui/popup

**Comment by harrisoncramer** [comment]
Yeah so the backup register is definitely going away eventually. I don't intend to keep around a configurable feature in this plugin that's only meant to deal with handling bugs, sorry, so my original comment still stands. And yeah I still don't love mixing types -- for this new feature please either do a table (probably better, it's more flexible) or a string, not both.

**Comment by harrisoncramer** [comment]
This has been addressed by Jakub's latest temporary registers MR, e.g. see `:h gitlab.nvim.temp-registers`

If I'm mistaken Jakub please let me know.

**Comment by briandipalma** [comment]
The documentation mentions both `temp_registers` and ``settings.popup.backup_register`, maybe that should be cleaned up.

**Comment by briandipalma** [comment]
https://github.com/harrisoncramer/gitlab.nvim/pull/259
