### ISSUE TITLE
gitlab.nvim: Failed to parse JSON from /users/me endpoint, got: '404 page not found'

### ISSUE THREAD

**Issue by Otterpatsch** [harrisoncramer/gitlab.nvim#191]
## Prerequsities

- [x] The "Troubleshooting" section of the README did not help ( i didnt found a Troubleshooting section in the README)
- [x] I've installed the required dependencies
- [x] I'm on the latest version of the plugin

## Bug Description

So im using a self hosted instance of gitlab and the /users/me doenst exists. But i know my user ID. Can i curcumvent and just hardcode somewhere my userID instead of sending that request?

## Reproduction Steps

1. Check out the feature branch
2. Open Neovim
3. :lua require("gitlab").review() 
4. get `gitlab.nvim: Failed to parse JSON from /users/me endpoint, got: '404 page not found'`

**Comment by harrisoncramer** [comment]
Hey @Otterpatsch,

Thanks for using this plugin. The 404 from the `users/me` endpoint indicates that you do not have the latest Go binary installed and running; I don't think this has anything to do with you using a self-hosted Gitlab instance. The 404 response is coming from the Go server. I'd try the following first and let me know if this solves things:

1. Recompile the Go binary: `:lua require("gitlab.server").build(true)`
2. Quit all your running Neovim instances
3. Reopen Neovim and run the `review` command.

Secondly, the Go binary should be re-compiled whenever you update the plugin. It's possible you're missing this required line from your plugin configuration (with Lazy):

```lua
build = function () require("gitlab.server").build(true) end, -- with lazy...
-- or with packer...
run = function() require("gitlab.server").build(true) end,
```

Finally, I'll make sure to update the Go server to respond to 404s with more helpful error messages, and I'll update the issue template to ask people to check `:h gitlab.nvim.troubleshooting` in the future, since the Readme has been modified since this template was first created.

Does this help?

**Comment by Otterpatsch** [comment]
It seems i had to also kick of a Update/Refresh via Lazy to rerun the build. NOw everthing works like a charm again
