### ISSUE TITLE
Allow to run on master/main branch

### ISSUE THREAD

**Issue by benedikt-bartscher** [harrisoncramer/gitlab.nvim#218]
## Feature Description

Add an option which disables the default branch check here: https://github.com/harrisoncramer/gitlab.nvim/blob/c0c67486d17d4f73f62b50c13c77aaed2e9f17f0/cmd/git.go#L90   
Is there a specific reason for this, or just to prevent unwanted action on main? It would be awesome if one could f.e. retrieve the pipeline status for main.

@harrisoncramer thanks for this awesome plugin, I love it! Happy holidays :palm_tree:

**Comment by harrisoncramer** [comment]
Hello,

Thanks for the kind wishes. This plugin is primarily focused right now on creating or reviewing merge requests, and as such was designed to only run on feature branches (for now). When the `go` server starts up it gets the `git` information about the current project (including the name of the MR, etc). 

In order to support running on `main` or `master` we'd have to come up with a way of avoiding this, and also resetting the branch information for a running `go` server after it's already started. This is doable, but not a high priority right now.

For now, if you want to check out the pipeline status of a `main` branch locally  without going to their website I'd recommend checking out the `glab` CLI tool. For instance this command does what you want:

```
glab pipeline ci view
```

**Comment by harrisoncramer** [comment]
@benedikt-bartscher This is now supported in `develop` and will merge into `main` soon.
