### ISSUE TITLE
Mappings to change focus

### ISSUE THREAD

**Issue by benedikt-bartscher** [harrisoncramer/gitlab.nvim#219]
Provide mappings to change focus f.e. from MR Title to Description using apis like `nvim_set_current_win(title_popup.winid)`.

**Comment by benedikt-bartscher** [comment]
Thank you, @jakubbortlik! I just tried `<c-j>` and `<c-k>` which did not work for some reason.

**Comment by jakubbortlik** [comment]
Hi @benedikt-bartscher if the builtin keymaps do what you need, can you please close this issue?

**Comment by benedikt-bartscher** [comment]
Hi @jakubbortlik they indeed work, however I would love to add support for nvims other window keymaps aswell.

**Comment by jakubbortlik** [comment]
HI @benedikt-bartscher, I think this request would be more appropriate at the [nui.nvim](https://github.com/MunifTanjim/nui.nvim) library. There already exists a closed [discussion](https://github.com/MunifTanjim/nui.nvim/discussions/289) with basically the same topic, but it was more of an inquiry rather than a feature request, and it was asked from the point of view of a plugin author.

"nvims other window keymaps" is rather broad. Is there something in particular that you'd like to be able to do in the MR summary popup? I don't see much use myself in supporting `<ctrl-w>j` and `<ctrl-w>k` when `<ctrl-w><ctrl-w>` and `<ctrl-w>W` do the job as well. But I can see that e.g., using the `<tab>` key to cycle through the windows in the summary would be practical (something like the [resolution](https://github.com/RobinTruax/resolution/blob/63cbc5a50eee8df039f54e593ed377f04e60e583/lua/computation/napkin/actions.lua#L63) plugin does). Maybe if you are more specific in your feature request, Harrison might reopen it. Or you could create a PR yourself, if you are interested.
