### ISSUE TITLE
Is it possible to view already merged MRs? [QUESTION]

### ISSUE THREAD

**Issue by sapelkinAV** [harrisoncramer/gitlab.nvim#321]
Greetings!
Thank you for developing such awesome plugin! 

I couldn't find in documentation and couldn't find ability to choose already merged MR. It's really tedious to do it in browser, and I think it would awesome experience to do it inside text editor. Maybe I missed something and it's possible already? I searched through closed issues, but it seems none asked about this. Sorry if missed.

Thank you and have a nice day!

**Comment by jakubbortlik** [comment]
Hi Alexander,
This is currently not possible but I've been thinking about opening a feature request for this too. Sometimes I need to go to closed MRs, e.g., to find something in the discussions of the MR, and I'd also prefer to do it in neovim rather than in the browser.
I'm not sure how much work this addition would require but I imagine it'd be fairly simple, just modifying the go server a little, exposing configuration in the setup function, and also visualizing this in the UI.
Would you like to open a PR for this? Harrison is always welcoming new contributors!

**Comment by sapelkinAV** [comment]
I will try to do it on weekend, but no promises. I just starting my experience with nvim, and have really small experience of debugging it. But I'll try) I'll text if something will work)

**Comment by jakubbortlik** [comment]
Hi @sapelkinAV, if you decide you want to work on a PR, please start by reading [CONTRIBUTING.md](https://github.com/harrisoncramer/gitlab.nvim/blob/main/.github/CONTRIBUTING.md) :)

**Comment by chardskarth** [comment]
Hi, my PR just got merged (#346). `choose_merge_requests` now accepts a table of params.
This should just be an additional parameter when filtering merge requests ([state parameter](https://docs.gitlab.com/ee/api/merge_requests.html#list-merge-requests))

**Comment by harrisoncramer** [comment]
This is now implemented in `develop` which I intend to release to main at some point next week. If you want this functionality now you can use the develop branch of the plugin by setting `branch = "develop"` in your Lazy configuration.

It's the staging ground for new features so is prone to breaking issues sometimes, fair warning.
