### ISSUE TITLE
Ability to choose Freestyle or from .gitlab/merge_request_templates/* if exists

### ISSUE THREAD

**Issue by davegec** [harrisoncramer/gitlab.nvim#332]
## Choose MR Description

Hi!
It would be nice to have the ability to select a description template from .gitlab/merge_request_templates, if the content exists, or write freestyle when opening a MR.

Other idea 
Use the latest commit message (ex. conventional commits style) for MR title and description 

Love the plugin

**Comment by jakubbortlik** [comment]
Hi @davegec, it is already possible since version 1.1.5 (December 2023) to choose from existing merge request templates, if there are any files in `.gitlab/merge_request_templates` in the project repo. Are you using the latest version of the plugin?

Regarding your other idea, would you be interested in preparing a PR for that feature? If yes, please start with reading [.github/CONTRIBUTING.md](https://github.com/harrisoncramer/gitlab.nvim/blob/main/.github/CONTRIBUTING.md).

**Comment by harrisoncramer** [comment]
This is already supported, closing this!
