### ISSUE TITLE
Default suggestion keymaps blocks LazyVim flash searching

### ISSUE THREAD

**Issue by briandipalma** [harrisoncramer/gitlab.nvim#347]
## Prerequsities

- [x] I'm on the latest version of the plugin
- [x] I've installed the required dependencies
- [x] I've run `:h gitlab.nvim.troubleshooting` and followed the steps there

## Setup Configuration and Environment

I'm trying to use the default config, so I deleted my keymaps.

## Bug Description

Not a bug, as you can change the keymaps but it's very common for `s` to be the flash.nvim trigger key which means the suggestion keymap breaks your ability to move around diffs and sometimes even opened files which is very jarring (I think there's a bug in diffview where buffer local settings can leak into opened files but I don't know how it's triggered). Although I'm not totally sure what keymap to suggest as an alternative to be honest I think it would be nice if it didn't clash. Maybe just use `cs` only and drop the top level  `s` keymap?

**Comment by harrisoncramer** [comment]
Hey Brian, thanks for filing the feedback. We _just_ added these default keymaps and this didn't come up during that MR review... I'm not inclined to change them again. The easiest fix here is just to change the mapping to something else if you use that particular plugin!

**Comment by jakubbortlik** [comment]
Hi, as for "the suggestion keymap breaks your ability to move around diffs and *sometimes even opened file*" - this may be caused by the `del_reviewer_keymaps` not to be called properly within the [callback for leaving the reviewer](https://github.com/harrisoncramer/gitlab.nvim/blob/aa5d3c1f523c969a4f381c57d00c9a206a6dc7e3/lua/gitlab/actions/discussions/init.lua#L86). It would help debug if you @brian could find a way to reproduce this.

Vim does not allpw setting a window-local keymap so that if you set a *buffer*-local mapping it is available in that buffer in any window/tab. I thought I fixed this by adding that callback that deletes the keymaps when leaving the reviewer, but appafently the autocommand does not fire always...

**Comment by briandipalma** [comment]
I've never really understood why this happens when using diffview but I'm used to it by now, see this issue https://github.com/sindrets/diffview.nvim/issues/330 which leaves me with absolute line numbers instead of relative. You appear to be relying on diffview so that explains why deleting the keymaps is randomly not triggering when you open a file from a diff. I'll try and see if I can recreate it consistently but I don't consider this a bug with gitlab.nvim. I think it's probably a diffview or Neovim bug so I'd be fine with closing this.
