### ISSUE TITLE
Cannot choose merge requests if there are multiple merge requests with the same source branches

### ISSUE THREAD

**Issue by mars90226** [harrisoncramer/gitlab.nvim#388]
## Prerequsities

- [x] I'm on the latest version of the plugin
- [x] I've installed the required dependencies
- [x] I've run `:h gitlab.nvim.troubleshooting` and followed the steps there

## Setup Configuration and Environment

```
{
    debug = { go_request = false, go_response = false },
    popup = {
      exit = "gq",
      backup_register = "+", -- NOTE: Default backup to system register, may hinder performance in WSL
    }
  }
```

## Bug Description

Cannot choose merge requests if there are multiple merge requests with the same source branches.

When executing `:lua require('gitlab').review`, gitlab.nvim will show the following error:
```
gitlab.nvim: Multiple MRs found: please call gitlab.choose_merge_request()
```
And executing `:lua require('gitlab').choose_merge_request()` and choose the MR, it still show the above error.

It occurs when the source branch of a merge request is deleted upon merging, and another MR is created with a newly created source branch that has the same name as the original.

I think the solution to this is to check if the merge request is merged or not and only check if the open merge requests is more than one in https://github.com/harrisoncramer/gitlab.nvim/blob/38bde8a0e4a982329ab4dc4f214f3f06dfc4e4fd/cmd/app/middleware.go#L123

## Reproduction Steps

1. Create a MR with branch `example`.
2. Merge with the option "delete source branch" checked.
3. Create another MR with branch `example`.
4. Checkout `example` branch.
5. Open Neovim
6. Execute `:lua require('gitlab').review()` or `:lua require('gitlab').choose_merge_request()` and select `example` branch.

## Screenshots

![圖片](https://github.com/user-attachments/assets/88088d96-117e-4d7f-90d1-eb262f435bb3)

**Comment by harrisoncramer** [comment]
Hey thanks for the bug report, I was able to replicate the problem here.

Just so I understand correctly, you are creating an MR with a branch name (say `some-branch`) then merging and deleting that branch on the remote, and then re-creating another MR with the same branch name? 

This is a pretty strange workflow! However, I think the fix here is to pass along the internal Id (IID) of the merge request to the Go server, rather than relying on the source and target branch, when a selection is made.

Please let me know if this solves your issue: 388-cannot-choose-merge-requests-if-multiple

**Comment by mars90226** [comment]
Thank you! I'll try if the new commit fix the bug and update here.
