### ISSUE TITLE
create_comment works only in review pannel

### ISSUE THREAD

**Issue by mrparalon** [harrisoncramer/gitlab.nvim#49]
On the latest version of plugin, `.create_comment()` works only from review panel.

Error message `Delta reviewer must be initialized first`

I'm using [diffview](https://github.com/sindrets/diffview.nvim) to review MRs.

Is it possible to make it work without Delta reviewer?

**Comment by harrisoncramer** [comment]
This is by design, the reason being that we need to get the current line information from the reviewer in order to make a comment to Github's APIs.

Please see this discussion for more context: https://github.com/harrisoncramer/gitlab.nvim/issues/25

If you wanted to to add a reviewer, it would have to implement the functions at `lua/gitlab/reviewer/init.lua` 

```lua

**Comment by mrparalon** [comment]
Thanks for direction, I'll try to add diffview reviewer
