### ISSUE TITLE
Reload .gitlab.toml

### ISSUE THREAD

**Issue by loyd** [harrisoncramer/gitlab.nvim#64]
Thanks for the plugin; it looks promising.

I use a project-per-tab approach and have a lot of different repositories. The problem is that `.gitlab.toml` is read once at startup in the directory where nvim is started. So, after switching to another tab with a different cwd, the `.gitlab.toml` in that repository isn't loaded.

Is it hard to implement, or maybe it can be configured already?

**Comment by harrisoncramer** [comment]
Hey Loyd, thanks for filing an issue. 

This plugin currently uses a `.gitlab.nvim` file, not a `.gitlab.toml` file to configure the server. So, you'd have to reload a different `.gitlab.nvim` file if you wanted, in order to start a new server.

It seems that you want to be able to run different Gitlab servers when you switch tabs in Neovim, without actually closing Neovim. This is not likely going to be supported in the near future. For now, you'll have to have different instances of Neovim running in different directories if you wanted different reviewers. This is being worked on here: 

https://github.com/harrisoncramer/gitlab.nvim/pull/65
