### ISSUE TITLE
Latest commit broke everything (a055c4c988e792fa8014421a7a51d140f490ea69)

### ISSUE THREAD

**Issue by gunslingerfry** [harrisoncramer/gitlab.nvim#70]
## Prerequsities

- [x] The "Troubleshooting" section of the README did not help
- [x] I've installed the required dependencies
- [x] I'm on the latest version of the plugin

## Bug Description

Looks like some debug code got committed uncommented or the debug command line options were added half-baked. After building the server (as shown in the troubleshooting) and starting fails to start. It checks if there are < 5 arguments but then checks the 6th for a debug option. Fixing that, the vim plugin has issues around concatenation of the debug option. I did not debug that issue,, however after checking out the previous commit (3a67424fec51012b9f9a3faf64a6e8e754056f73) the plugin works as expected.

**Comment by harrisoncramer** [comment]
Thank you for reporting this. I was able to replicate the issue due to your note and merged in a change that should resolve this issue. Please update the plugin and let me know if that solves things for you.

https://github.com/harrisoncramer/gitlab.nvim/pull/73

Sorry about this! I'll try to be more careful in the future, did not realize that this change would have an impact on the request context.

**Comment by gunslingerfry** [comment]
That works! Thank you!
