### ISSUE TITLE
Syntax highlighting in discussion tree

### ISSUE THREAD

**Issue by mrparalon** [harrisoncramer/gitlab.nvim#80]
## Feature Description

Now all discussion tree is a plain text. It is a bit hard to read, if you have long threads with code snippents and multiple participants

What could be useful

- Highlight user tags. Unique color for each user would really cool
- Highlight dates and how long time ago comment was made
- Markdown syntax highlighting

**Comment by harrisoncramer** [comment]
I've just merged in an MR that implements user-tag highlighting, dates since comment, the chevrons for opening/closing discussions, and markdown syntax highlighting. Please feel free to open up another issue if you'd like to add to it further.

I'm not intending to implement per-user color highlighting, that's something users would have to configure on their own.
