### ISSUE TITLE
use a binary in PATH

### ISSUE THREAD

**Issue by teto** [harrisoncramer/gitlab.nvim#85]
## Feature Description
I would like to use gitlab.nvim with a prebuild binary "bin" (I dont have go in PATH). Is there a way to tell the plugin the path to the binary or have the plugin use the binary in PATH (but this may imply to change the name as "bin" is awkard)

**Comment by harrisoncramer** [comment]
Hey,

Having Go in your path is kind of a prerequisite for this plugin to work, because every time we release a new version (bug fixes, new features, etc) or you install the plugin, it'll rebuild the binary on your machine. If you're missing Go from your path then we can't trigger that build step.

You might be able to get around this by removing the `build` line from your configuration, and then changing into the directory of the Go source code (will depend on whether you're using Packer or Lazy) and building it yourself -- but in that case you're going to have to build the plugin on your machine using Go anyway. 

We could try to support shipping binaries along with the plugin in the future, but that'd be a new feature (it would remove the Go dependency but would introduce a lot of complexity for different operating systems).

**Comment by l-lin** [comment]
:wave: 

Thank you for this awesome plugin!

I was wondering what was the motivations to have a Go server instead of using pure Lua to perform HTTP requests to the Gitlab instance, hence reducing external dependencies?
Was there a technical challenge that needed a middleware between Nvim and Gitlab? Or maybe is it just easier to implement the requests to Gitlab (e.g. using existing open source library like go-gitlab)?

Just curious, not asking to change anything :wink:

**Comment by harrisoncramer** [comment]
Hey @teto would you take a look at the attached MR and let me know whether this addresses your use case? 

I'd like to avoid distributing binaries in the repository itself for the Go server if possible, since I think they may confuse the majority of users who are using the plugin as originally intended (allowing Lazy or Packer to rebuild the binary automatically).

**Comment by teto** [comment]
@harrisoncramer ideally I install vim plugins with dependencies via my package manager nix https://nixos.org/. It has a lot of advantages compared to lazy.nvim & co (it's reproducible, I can cache binaries etc).

I like to configure the plugin without or complementary to nix though because it's easier to iterate on configuration. So I would like to be able to split my configuration for instance such that nix can assign the path to the binary in a generated init.lua via `vim.g.gitlab.bin_path = .../bin` while the rest of my config lives my init-manual.lua . The `setup` paradigm doesnt help in that regard, you can read https://mrcjkb.dev/posts/2023-08-22-setup.html for instance.

Alternatives that we use to package vim plugins in nix:
- wrap the nvim executable with a PATH that contain the executable: works only if the plugin looks for executable in PATH
- hardcode the path as done here for instance https://github.com/NixOS/nixpkgs/blob/d26c4cb24dbe52fac1fa660f21a561b25f711a5d/pkgs/applications/editors/vim/plugins/overrides.nix#L211

**Comment by harrisoncramer** [comment]
Okay! This isn't something I'm going to continue working on, but if you wanted to submit a PR to this repository that adds/enables your desired installation functionality alongside the existing installation options, I'd be happy to review it; I'm not a user of NixOS and probably not the right person to implement what you want.
